baseURL = "https://unswcpmsoc.com/"
languageCode = "en-us"
title = "UNSW Competitive Programming and Mathematics Society"
theme = "cpmsoc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

# Main menu dropdown  items
[[menu.main]]
identifier = "resources"
name = "Resources"
weight = 2

[[menu.main]]
identifier = "events"
name = "Events"
weight = 3

[[menu.main]]
identifier = "aboutus"
name = "About Us"
weight = 4 

# Add blogs to resources
[[menu.main]]
identifier = "blog"
name = "Blog"
parent = "resources"
url = "https://blog.unswcpmsoc.com/"
weight = 4

# Add workshops again to events
# [[menu.main]]
# identifier = "workshops"
# name = "Past Workshops"
# parent = "events"
# url = "/workshops/"


  