[[redirects]]
from = "/discord"
to = "https://discord.gg/9uxgxHY3pP"

[[redirects]]
from = "/facebook"
to = "https://www.facebook.com/CPMSoc/"

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/cpmsoc_unsw/"

[[redirects]]
from = "/newsletter"
to = "https://forms.gle/L9VeEY8ZDqYKDyha6"

[[redirects]]
from = "/apply"
to = " https://forms.gle/Gy9vLp2XEfTW6Le36"

[[redirects]]
from = "/attendance"
to = "https://forms.gle/X7pLQrU611K6VWsA6"

[[redirects]]
from = "/feedback"
to = "https://forms.gle/a8TAMjrpEWSD3TWj6"

[[redirects]]
from = "/guide"
to = "https://www.canva.com/design/DAGcjD1Ty-U/0D3aYo0iTo2TSEPV9JTV1g/view?utm_content=DAGcjD1Ty-U&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h89a3b7427e"
